version: '3.4'

services:
  sentiment-analysis:
    image: sentiment-analysis-from-text
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: sentiment-analysis
    command:
      [
        "sh",
        "-c",
        "uvicorn wsgi:app --host 0.0.0.0 --port 4080"
      ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 4080:4080
    expose:
      - 4080
 
